[package]
name = "libcaesium_dart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.4.0"
libcaesium = { git = "https://github.com/Lymphatus/libcaesium.git", tag = "0.16.4" }
tiff = "0.9.1"
